// <auto-generated>
//   This code was generated by openapi2zig 0.5.5 (99f6b79) on 2026-09-04 12:15:47 UTC
//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated
//   Checksum: 487d1c750b7fd4d4
// </auto-generated>

const std = @import("std");

pub const @"pages-https-certificate" = struct {
    description: []const u8,
    expires_at: ?[]const u8 = null,
    state: []const u8,
    domains: []const []const u8,
};

pub const status = struct {
    created_at: []const u8,
    url: []const u8,
    context: []const u8,
    state: []const u8,
    node_id: []const u8,
    target_url: ?[]const u8,
    description: ?[]const u8,
    avatar_url: ?[]const u8,
    id: i64,
    creator: @"nullable-simple-user",
    updated_at: []const u8,
};

pub const @"prevent-self-review" = bool;

pub const IssuePullRequest = struct {
    patch_url: ?[]const u8,
    diff_url: ?[]const u8,
    url: ?[]const u8,
    html_url: ?[]const u8,
    merged_at: ?[]const u8 = null,
};

pub const issue = struct {
    comments: i64,
    url: []const u8,
    pull_request: ?IssuePullRequest = null,
    pinned_comment: ?@"nullable-issue-comment" = null,
    body_html: ?[]const u8 = null,
    active_lock_reason: ?[]const u8 = null,
    issue_dependencies_summary: ?@"issue-dependencies-summary" = null,
    assignee: @"nullable-simple-user",
    comments_url: []const u8,
    id: i64,
    number: i64,
    reactions: ?@"reaction-rollup" = null,
    node_id: []const u8,
    body: ?[]const u8 = null,
    type: ?@"issue-type" = null,
    draft: ?bool = null,
    created_at: []const u8,
    timeline_url: ?[]const u8 = null,
    state: []const u8,
    state_reason: ?[]const u8 = null,
    assignees: ?[]const @"simple-user" = null,
    repository_url: []const u8,
    events_url: []const u8,
    milestone: @"nullable-milestone",
    locked: bool,
    body_text: ?[]const u8 = null,
    user: @"nullable-simple-user",
    performed_via_github_app: ?@"nullable-integration" = null,
    updated_at: []const u8,
    repository: ?repository = null,
    issue_field_values: ?[]const @"issue-field-value" = null,
    labels_url: []const u8,
    html_url: []const u8,
    labels: []const std.json.Value,
    author_association: ?[]const u8 = null,
    parent_issue_url: ?[]const u8 = null,
    closed_at: ?[]const u8,
    closed_by: ?@"nullable-simple-user" = null,
    sub_issues_summary: ?@"sub-issues-summary" = null,
    title: []const u8,
};

pub const @"issue-event-milestone" = struct {
    title: []const u8,
};

pub const TeamPermissions = struct {
    push: bool,
    admin: bool,
    maintain: bool,
    triage: bool,
    pull: bool,
};

pub const team = struct {
    enterprise_id: ?i64 = null,
    url: []const u8,
    permissions: ?TeamPermissions = null,
    privacy: ?[]const u8 = null,
    id: i64,
    members_url: []const u8,
    notification_setting: ?[]const u8 = null,
    parent: @"nullable-team-simple",
    html_url: []const u8,
    node_id: []const u8,
    access_source: ?[]const u8 = null,
    repositories_url: []const u8,
    description: ?[]const u8,
    organization_id: ?i64 = null,
    permission: []const u8,
    name: []const u8,
    type: []const u8,
    slug: []const u8,
};

pub const @"check-immutable-releases" = struct {
    enforced_by_owner: bool,
    enabled: bool,
};

pub const TagCommit = struct {
    sha: []const u8,
    url: []const u8,
};

pub const tag = struct {
    tarball_url: []const u8,
    commit: TagCommit,
    name: []const u8,
    node_id: []const u8,
    zipball_url: []const u8,
};

pub const ProtectedBranchRequiredStatusCheckChecksItem = struct {
    context: []const u8,
    app_id: ?i64,
};

pub const @"protected-branch-required-status-check" = struct {
    url: ?[]const u8 = null,
    contexts: []const []const u8,
    checks: []const ProtectedBranchRequiredStatusCheckChecksItem,
    enforcement_level: ?[]const u8 = null,
    contexts_url: ?[]const u8 = null,
    strict: ?bool = null,
};

pub const ValidationErrorErrorsItem = struct {
    resource: ?[]const u8 = null,
    value: ?std.json.Value = null,
    field: ?[]const u8 = null,
    message: ?[]const u8 = null,
    index: ?i64 = null,
    code: []const u8,
};

pub const @"validation-error" = struct {
    errors: ?[]const ValidationErrorErrorsItem = null,
    message: []const u8,
    documentation_url: []const u8,
};

pub const CommitParentsItem = struct {
    sha: []const u8,
    url: []const u8,
    html_url: ?[]const u8 = null,
};

pub const CommitStats = struct {
    deletions: ?i64 = null,
    additions: ?i64 = null,
    total: ?i64 = null,
};

pub const CommitCommitTree = struct {
    sha: []const u8,
    url: []const u8,
};

pub const CommitCommit = struct {
    author: @"nullable-git-user",
    url: []const u8,
    tree: CommitCommitTree,
    verification: ?verification = null,
    comment_count: i64,
    committer: @"nullable-git-user",
    message: []const u8,
};

pub const commit = struct {
    author: ?std.json.Value,
    parents: []const CommitParentsItem,
    url: []const u8,
    stats: ?CommitStats = null,
    html_url: []const u8,
    node_id: []const u8,
    files: ?[]const @"diff-entry" = null,
    sha: []const u8,
    committer: ?std.json.Value,
    commit: CommitCommit,
    comments_url: []const u8,
};

pub const NullableCollaboratorPermissions = struct {
    push: bool,
    admin: bool,
    maintain: ?bool = null,
    triage: ?bool = null,
    pull: bool,
};

pub const @"nullable-collaborator" = struct {
    url: []const u8,
    subscriptions_url: []const u8,
    organizations_url: []const u8,
    email: ?[]const u8 = null,
    login: []const u8,
    gists_url: []const u8,
    events_url: []const u8,
    gravatar_id: ?[]const u8,
    id: i64,
    repos_url: []const u8,
    permissions: ?NullableCollaboratorPermissions = null,
    role_name: []const u8,
    followers_url: []const u8,
    starred_url: []const u8,
    html_url: []const u8,
    node_id: []const u8,
    site_admin: bool,
    user_view_type: ?[]const u8 = null,
    following_url: []const u8,
    avatar_url: []const u8,
    name: ?[]const u8 = null,
    received_events_url: []const u8,
    type: []const u8,
};

pub const BranchWithProtectionLinks = struct {
    self: []const u8,
    html: []const u8,
};

pub const @"branch-with-protection" = struct {
    _links: BranchWithProtectionLinks,
    protection: @"branch-protection",
    protection_url: []const u8,
    required_approving_review_count: ?i64 = null,
    pattern: ?[]const u8 = null,
    commit: commit,
    name: []const u8,
    protected: bool,
};

pub const @"repository-rule-detailed" = union(enum) {
    null,
    bool: bool,
    integer: i64,
    float: f64,
    number_string: []const u8,
    string: []const u8,
    array: std.json.Array,
    object: std.json.ObjectMap,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(_: std.mem.Allocator, source: std.json.Value, _: std.json.ParseOptions) !@This() {
        return switch (source) {
            .null => .null,
            .bool => |value| .{ .bool = value },
            .integer => |value| .{ .integer = value },
            .float => |value| .{ .float = value },
            .number_string => |value| .{ .number_string = value },
            .string => |value| .{ .string = value },
            .array => |value| .{ .array = value },
            .object => |value| .{ .object = value },
        };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .null => try jw.write(null),
            .bool => |value| try jw.write(value),
            .integer => |value| try jw.write(value),
            .float => |value| try jw.write(value),
            .number_string => |value| try jw.print("{s}", .{value}),
            .string => |value| try jw.write(value),
            .array => |value| try jw.write(value.items),
            .object => |value| {
                try jw.beginObject();
                var iterator = value.iterator();
                while (iterator.next()) |entry| {
                    try jw.objectField(entry.key_ptr.*);
                    try jw.write(entry.value_ptr.*);
                }
                try jw.endObject();
            },
        }
    }
};

pub const @"repository-rule" = union(enum) {
    null,
    bool: bool,
    integer: i64,
    float: f64,
    number_string: []const u8,
    string: []const u8,
    array: std.json.Array,
    object: std.json.ObjectMap,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(_: std.mem.Allocator, source: std.json.Value, _: std.json.ParseOptions) !@This() {
        return switch (source) {
            .null => .null,
            .bool => |value| .{ .bool = value },
            .integer => |value| .{ .integer = value },
            .float => |value| .{ .float = value },
            .number_string => |value| .{ .number_string = value },
            .string => |value| .{ .string = value },
            .array => |value| .{ .array = value },
            .object => |value| .{ .object = value },
        };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .null => try jw.write(null),
            .bool => |value| try jw.write(value),
            .integer => |value| try jw.write(value),
            .float => |value| try jw.write(value),
            .number_string => |value| try jw.print("{s}", .{value}),
            .string => |value| try jw.write(value),
            .array => |value| try jw.write(value.items),
            .object => |value| {
                try jw.beginObject();
                var iterator = value.iterator();
                while (iterator.next()) |entry| {
                    try jw.objectField(entry.key_ptr.*);
                    try jw.write(entry.value_ptr.*);
                }
                try jw.endObject();
            },
        }
    }
};

pub const @"issue-dependencies-summary" = struct {
    total_blocked_by: i64,
    blocked_by: i64,
    total_blocking: i64,
    blocking: i64,
};

pub const PullRequestSimpleBase = struct {
    sha: []const u8,
    ref: []const u8,
    label: []const u8,
    repo: repository,
    user: @"nullable-simple-user",
};

pub const PullRequestSimpleLinks = struct {
    statuses: link,
    comments: link,
    review_comments: link,
    review_comment: link,
    html: link,
    self: link,
    issue: link,
    commits: link,
};

pub const PullRequestSimpleLabelsItem = struct {
    default: bool,
    url: []const u8,
    color: []const u8,
    node_id: []const u8,
    description: []const u8,
    id: i64,
    name: []const u8,
};

pub const PullRequestSimpleHead = struct {
    sha: []const u8,
    ref: []const u8,
    label: []const u8,
    repo: repository,
    user: @"nullable-simple-user",
};

pub const @"pull-request-simple" = struct {
    url: []const u8,
    requested_teams: ?[]const team = null,
    statuses_url: []const u8,
    assignee: @"nullable-simple-user",
    active_lock_reason: ?[]const u8 = null,
    comments_url: []const u8,
    id: i64,
    base: PullRequestSimpleBase,
    number: i64,
    _links: PullRequestSimpleLinks,
    review_comment_url: []const u8,
    node_id: []const u8,
    body: ?[]const u8,
    draft: ?bool = null,
    review_comments_url: []const u8,
    created_at: []const u8,
    issue_url: []const u8,
    auto_merge: @"auto-merge",
    state: []const u8,
    assignees: ?[]const @"simple-user" = null,
    milestone: @"nullable-milestone",
    diff_url: []const u8,
    locked: bool,
    user: @"nullable-simple-user",
    merge_commit_sha: ?[]const u8,
    updated_at: []const u8,
    patch_url: []const u8,
    requested_reviewers: ?[]const @"simple-user" = null,
    labels: []const PullRequestSimpleLabelsItem,
    html_url: []const u8,
    head: PullRequestSimpleHead,
    author_association: []const u8,
    stack: ?@"pull-request-stack" = null,
    commits_url: []const u8,
    closed_at: ?[]const u8,
    merged_at: ?[]const u8,
    title: []const u8,
};

pub const @"team-simple" = struct {
    enterprise_id: ?i64 = null,
    url: []const u8,
    privacy: ?[]const u8 = null,
    id: i64,
    members_url: []const u8,
    notification_setting: ?[]const u8 = null,
    ldap_dn: ?[]const u8 = null,
    html_url: []const u8,
    node_id: []const u8,
    repositories_url: []const u8,
    description: ?[]const u8,
    organization_id: ?i64 = null,
    permission: []const u8,
    name: []const u8,
    type: []const u8,
    slug: []const u8,
};

pub const link = struct {
    href: []const u8,
};

pub const PagesHealthCheckAltDomain = struct {
    enforces_https: ?bool = null,
    has_cname_record: ?bool = null,
    is_valid: ?bool = null,
    is_old_ip_address: ?bool = null,
    is_a_record: ?bool = null,
    is_fastly_ip: ?bool = null,
    nameservers: ?[]const u8 = null,
    is_apex_domain: ?bool = null,
    is_pointed_to_github_pages_ip: ?bool = null,
    is_non_github_pages_ip_present: ?bool = null,
    is_pages_domain: ?bool = null,
    uri: ?[]const u8 = null,
    is_served_by_pages: ?bool = null,
    host: ?[]const u8 = null,
    is_cname_to_github_user_domain: ?bool = null,
    is_cname_to_fastly: ?bool = null,
    responds_to_https: ?bool = null,
    caa_error: ?[]const u8 = null,
    has_mx_records_present: ?bool = null,
    is_cname_to_pages_dot_github_dot_com: ?bool = null,
    https_error: ?[]const u8 = null,
    should_be_a_record: ?bool = null,
    is_valid_domain: ?bool = null,
    reason: ?[]const u8 = null,
    dns_resolves: ?bool = null,
    is_proxied: ?bool = null,
    is_https_eligible: ?bool = null,
    is_cloudflare_ip: ?bool = null,
};

pub const PagesHealthCheckDomain = struct {
    enforces_https: ?bool = null,
    has_cname_record: ?bool = null,
    is_valid: ?bool = null,
    is_old_ip_address: ?bool = null,
    is_a_record: ?bool = null,
    is_fastly_ip: ?bool = null,
    nameservers: ?[]const u8 = null,
    is_apex_domain: ?bool = null,
    is_pointed_to_github_pages_ip: ?bool = null,
    is_non_github_pages_ip_present: ?bool = null,
    is_pages_domain: ?bool = null,
    uri: ?[]const u8 = null,
    is_served_by_pages: ?bool = null,
    host: ?[]const u8 = null,
    is_cname_to_github_user_domain: ?bool = null,
    is_cname_to_fastly: ?bool = null,
    responds_to_https: ?bool = null,
    caa_error: ?[]const u8 = null,
    has_mx_records_present: ?bool = null,
    is_cname_to_pages_dot_github_dot_com: ?bool = null,
    https_error: ?[]const u8 = null,
    should_be_a_record: ?bool = null,
    is_valid_domain: ?bool = null,
    reason: ?[]const u8 = null,
    dns_resolves: ?bool = null,
    is_proxied: ?bool = null,
    is_https_eligible: ?bool = null,
    is_cloudflare_ip: ?bool = null,
};

pub const @"pages-health-check" = struct {
    alt_domain: ?PagesHealthCheckAltDomain = null,
    domain: ?PagesHealthCheckDomain = null,
};

pub const RepositoryRulesetConditionsRefName = struct {
    include: ?[]const []const u8 = null,
    exclude: ?[]const []const u8 = null,
};

pub const @"repository-ruleset-conditions" = struct {
    ref_name: ?RepositoryRulesetConditionsRefName = null,
};

pub const @"diff-entry" = struct {
    contents_url: []const u8,
    deletions: i64,
    patch: ?[]const u8 = null,
    sha: ?[]const u8,
    status: []const u8,
    filename: []const u8,
    additions: i64,
    previous_filename: ?[]const u8 = null,
    changes: i64,
    blob_url: []const u8,
    raw_url: []const u8,
};

pub const @"webhook-config-url" = []const u8;

pub const NullableIssuePullRequest = struct {
    patch_url: ?[]const u8,
    diff_url: ?[]const u8,
    url: ?[]const u8,
    html_url: ?[]const u8,
    merged_at: ?[]const u8 = null,
};

pub const @"nullable-issue" = struct {
    comments: i64,
    url: []const u8,
    pull_request: ?NullableIssuePullRequest = null,
    pinned_comment: ?@"nullable-issue-comment" = null,
    body_html: ?[]const u8 = null,
    active_lock_reason: ?[]const u8 = null,
    issue_dependencies_summary: ?@"issue-dependencies-summary" = null,
    assignee: @"nullable-simple-user",
    comments_url: []const u8,
    id: i64,
    number: i64,
    reactions: ?@"reaction-rollup" = null,
    node_id: []const u8,
    body: ?[]const u8 = null,
    type: ?@"issue-type" = null,
    draft: ?bool = null,
    created_at: []const u8,
    timeline_url: ?[]const u8 = null,
    state: []const u8,
    state_reason: ?[]const u8 = null,
    assignees: ?[]const @"simple-user" = null,
    repository_url: []const u8,
    events_url: []const u8,
    milestone: @"nullable-milestone",
    locked: bool,
    body_text: ?[]const u8 = null,
    user: @"nullable-simple-user",
    performed_via_github_app: ?@"nullable-integration" = null,
    updated_at: []const u8,
    repository: ?repository = null,
    issue_field_values: ?[]const @"issue-field-value" = null,
    labels_url: []const u8,
    html_url: []const u8,
    labels: []const std.json.Value,
    author_association: ?[]const u8 = null,
    parent_issue_url: ?[]const u8 = null,
    closed_at: ?[]const u8,
    closed_by: ?@"nullable-simple-user" = null,
    sub_issues_summary: ?@"sub-issues-summary" = null,
    title: []const u8,
};

pub const @"simple-commit-status" = struct {
    created_at: []const u8,
    context: []const u8,
    url: []const u8,
    state: []const u8,
    node_id: []const u8,
    target_url: ?[]const u8,
    required: ?bool = null,
    description: ?[]const u8,
    avatar_url: ?[]const u8,
    id: i64,
    updated_at: []const u8,
};

pub const language = union(enum) {
    null,
    bool: bool,
    integer: i64,
    float: f64,
    number_string: []const u8,
    string: []const u8,
    array: std.json.Array,
    object: std.json.ObjectMap,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(_: std.mem.Allocator, source: std.json.Value, _: std.json.ParseOptions) !@This() {
        return switch (source) {
            .null => .null,
            .bool => |value| .{ .bool = value },
            .integer => |value| .{ .integer = value },
            .float => |value| .{ .float = value },
            .number_string => |value| .{ .number_string = value },
            .string => |value| .{ .string = value },
            .array => |value| .{ .array = value },
            .object => |value| .{ .object = value },
        };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .null => try jw.write(null),
            .bool => |value| try jw.write(value),
            .integer => |value| try jw.write(value),
            .float => |value| try jw.write(value),
            .number_string => |value| try jw.print("{s}", .{value}),
            .string => |value| try jw.write(value),
            .array => |value| try jw.write(value.items),
            .object => |value| {
                try jw.beginObject();
                var iterator = value.iterator();
                while (iterator.next()) |entry| {
                    try jw.objectField(entry.key_ptr.*);
                    try jw.write(entry.value_ptr.*);
                }
                try jw.endObject();
            },
        }
    }
};

pub const @"reaction-rollup" = struct {
    @"-1": i64,
    heart: i64,
    url: []const u8,
    @"+1": i64,
    hooray: i64,
    eyes: i64,
    confused: i64,
    rocket: i64,
    laugh: i64,
    total_count: i64,
};

pub const @"repository-rule-enforcement" = []const u8;

pub const @"pages-source-hash" = struct {
    path: []const u8,
    branch: []const u8,
};

pub const FileCommitCommitAuthor = struct {
    date: ?[]const u8 = null,
    name: ?[]const u8 = null,
    email: ?[]const u8 = null,
};

pub const FileCommitCommitParentsItem = struct {
    sha: ?[]const u8 = null,
    url: ?[]const u8 = null,
    html_url: ?[]const u8 = null,
};

pub const FileCommitCommitTree = struct {
    sha: ?[]const u8 = null,
    url: ?[]const u8 = null,
};

pub const FileCommitCommitVerification = struct {
    payload: ?[]const u8 = null,
    verified: ?bool = null,
    reason: ?[]const u8 = null,
    signature: ?[]const u8 = null,
    verified_at: ?[]const u8 = null,
};

pub const FileCommitCommitCommitter = struct {
    date: ?[]const u8 = null,
    name: ?[]const u8 = null,
    email: ?[]const u8 = null,
};

pub const FileCommitCommit = struct {
    author: ?FileCommitCommitAuthor = null,
    parents: ?[]const FileCommitCommitParentsItem = null,
    url: ?[]const u8 = null,
    tree: ?FileCommitCommitTree = null,
    html_url: ?[]const u8 = null,
    node_id: ?[]const u8 = null,
    verification: ?FileCommitCommitVerification = null,
    sha: ?[]const u8 = null,
    committer: ?FileCommitCommitCommitter = null,
    message: ?[]const u8 = null,
};

pub const FileCommitContentLinks = struct {
    self: ?[]const u8 = null,
    git: ?[]const u8 = null,
    html: ?[]const u8 = null,
};

pub const FileCommitContent = struct {
    size: ?i64 = null,
    _links: ?FileCommitContentLinks = null,
    url: ?[]const u8 = null,
    html_url: ?[]const u8 = null,
    sha: ?[]const u8 = null,
    path: ?[]const u8 = null,
    name: ?[]const u8 = null,
    git_url: ?[]const u8 = null,
    download_url: ?[]const u8 = null,
    type: ?[]const u8 = null,
};

pub const @"file-commit" = struct {
    commit: FileCommitCommit,
    content: ?FileCommitContent,
};

pub const @"nullable-team-simple" = struct {
    enterprise_id: ?i64 = null,
    url: []const u8,
    privacy: ?[]const u8 = null,
    id: i64,
    members_url: []const u8,
    notification_setting: ?[]const u8 = null,
    ldap_dn: ?[]const u8 = null,
    html_url: []const u8,
    node_id: []const u8,
    repositories_url: []const u8,
    description: ?[]const u8,
    organization_id: ?i64 = null,
    permission: []const u8,
    name: []const u8,
    type: []const u8,
    slug: []const u8,
};

pub const @"code-of-conduct-simple" = struct {
    url: []const u8,
    key: []const u8,
    name: []const u8,
    html_url: ?[]const u8,
};

pub const @"wait-timer" = i64;

pub const BranchRestrictionPolicyAppsItemOwner = struct {
    url: ?[]const u8 = null,
    subscriptions_url: ?[]const u8 = null,
    gists_url: ?[]const u8 = null,
    login: ?[]const u8 = null,
    hooks_url: ?[]const u8 = null,
    events_url: ?[]const u8 = null,
    issues_url: ?[]const u8 = null,
    repos_url: ?[]const u8 = null,
    id: ?i64 = null,
    public_members_url: ?[]const u8 = null,
    members_url: ?[]const u8 = null,
    gravatar_id: ?[]const u8 = null,
    followers_url: ?[]const u8 = null,
    organizations_url: ?[]const u8 = null,
    starred_url: ?[]const u8 = null,
    html_url: ?[]const u8 = null,
    node_id: ?[]const u8 = null,
    site_admin: ?bool = null,
    user_view_type: ?[]const u8 = null,
    description: ?[]const u8 = null,
    following_url: ?[]const u8 = null,
    avatar_url: ?[]const u8 = null,
    received_events_url: ?[]const u8 = null,
    type: ?[]const u8 = null,
};

pub const BranchRestrictionPolicyAppsItemPermissions = struct {
    single_file: ?[]const u8 = null,
    issues: ?[]const u8 = null,
    metadata: ?[]const u8 = null,
    contents: ?[]const u8 = null,
};

pub const BranchRestrictionPolicyAppsItem = struct {
    created_at: ?[]const u8 = null,
    client_id: ?[]const u8 = null,
    owner: ?BranchRestrictionPolicyAppsItemOwner = null,
    permissions: ?BranchRestrictionPolicyAppsItemPermissions = null,
    events: ?[]const []const u8 = null,
    id: ?i64 = null,
    updated_at: ?[]const u8 = null,
    html_url: ?[]const u8 = null,
    node_id: ?[]const u8 = null,
    description: ?[]const u8 = null,
    name: ?[]const u8 = null,
    external_url: ?[]const u8 = null,
    slug: ?[]const u8 = null,
};

pub const BranchRestrictionPolicyUsersItem = struct {
    url: ?[]const u8 = null,
    subscriptions_url: ?[]const u8 = null,
    organizations_url: ?[]const u8 = null,
    login: ?[]const u8 = null,
    gists_url: ?[]const u8 = null,
    events_url: ?[]const u8 = null,
    gravatar_id: ?[]const u8 = null,
    id: ?i64 = null,
    repos_url: ?[]const u8 = null,
    followers_url: ?[]const u8 = null,
    starred_url: ?[]const u8 = null,
    html_url: ?[]const u8 = null,
    node_id: ?[]const u8 = null,
    site_admin: ?bool = null,
    user_view_type: ?[]const u8 = null,
    following_url: ?[]const u8 = null,
    avatar_url: ?[]const u8 = null,
    received_events_url: ?[]const u8 = null,
    type: ?[]const u8 = null,
};

pub const @"branch-restriction-policy" = struct {
    url: []const u8,
    apps: []const BranchRestrictionPolicyAppsItem,
    users: []const BranchRestrictionPolicyUsersItem,
    teams_url: []const u8,
    apps_url: []const u8,
    teams: []const team,
    users_url: []const u8,
};

pub const @"simple-repository" = struct {
    private: bool,
    forks_url: []const u8,
    url: []const u8,
    assignees_url: []const u8,
    blobs_url: []const u8,
    fork: bool,
    issue_comment_url: []const u8,
    statuses_url: []const u8,
    compare_url: []const u8,
    comments_url: []const u8,
    id: i64,
    stargazers_url: []const u8,
    languages_url: []const u8,
    subscribers_url: []const u8,
    node_id: []const u8,
    description: ?[]const u8,
    git_tags_url: []const u8,
    subscription_url: []const u8,
    downloads_url: []const u8,
    contents_url: []const u8,
    pulls_url: []const u8,
    tags_url: []const u8,
    trees_url: []const u8,
    archive_url: []const u8,
    contributors_url: []const u8,
    owner: @"simple-user",
    git_commits_url: []const u8,
    hooks_url: []const u8,
    events_url: []const u8,
    issues_url: []const u8,
    keys_url: []const u8,
    full_name: []const u8,
    notifications_url: []const u8,
    releases_url: []const u8,
    branches_url: []const u8,
    labels_url: []const u8,
    html_url: []const u8,
    issue_events_url: []const u8,
    milestones_url: []const u8,
    teams_url: []const u8,
    commits_url: []const u8,
    collaborators_url: []const u8,
    deployments_url: []const u8,
    name: []const u8,
    git_refs_url: []const u8,
    merges_url: []const u8,
};

pub const @"combined-commit-status" = struct {
    statuses: []const @"simple-commit-status",
    repository: @"minimal-repository",
    url: []const u8,
    state: []const u8,
    sha: []const u8,
    commit_url: []const u8,
    total_count: i64,
};

pub const @"content-traffic" = struct {
    uniques: i64,
    path: []const u8,
    title: []const u8,
    count: i64,
};

pub const IntegrationPermissions = struct {
    issues: ?[]const u8 = null,
    checks: ?[]const u8 = null,
    metadata: ?[]const u8 = null,
    deployments: ?[]const u8 = null,
    contents: ?[]const u8 = null,
};

pub const integration = struct {
    created_at: []const u8,
    client_id: ?[]const u8 = null,
    owner: std.json.Value,
    permissions: IntegrationPermissions,
    events: []const []const u8,
    id: i64,
    updated_at: []const u8,
    html_url: []const u8,
    node_id: []const u8,
    installations_count: ?i64 = null,
    description: ?[]const u8,
    name: []const u8,
    external_url: []const u8,
    slug: ?[]const u8 = null,
};

pub const @"deployment-branch-policy" = struct {
    id: ?i64 = null,
    node_id: ?[]const u8 = null,
    name: ?[]const u8 = null,
    type: ?[]const u8 = null,
};

pub const CollaboratorPermissions = struct {
    push: bool,
    admin: bool,
    maintain: ?bool = null,
    triage: ?bool = null,
    pull: bool,
};

pub const collaborator = struct {
    url: []const u8,
    subscriptions_url: []const u8,
    organizations_url: []const u8,
    email: ?[]const u8 = null,
    login: []const u8,
    gists_url: []const u8,
    events_url: []const u8,
    gravatar_id: ?[]const u8,
    id: i64,
    repos_url: []const u8,
    permissions: ?CollaboratorPermissions = null,
    role_name: []const u8,
    followers_url: []const u8,
    starred_url: []const u8,
    html_url: []const u8,
    node_id: []const u8,
    site_admin: bool,
    user_view_type: ?[]const u8 = null,
    following_url: []const u8,
    avatar_url: []const u8,
    name: ?[]const u8 = null,
    received_events_url: []const u8,
    type: []const u8,
};

pub const RepositoryPermissions = struct {
    push: bool,
    admin: bool,
    maintain: ?bool = null,
    triage: ?bool = null,
    pull: bool,
};

pub const RepositoryCodeSearchIndexStatus = struct {
    lexical_search_ok: ?bool = null,
    lexical_commit_sha: ?[]const u8 = null,
};

pub const repository = struct {
    deployments_url: []const u8,
    pull_request_creation_policy: ?[]const u8 = null,
    has_wiki: bool,
    assignees_url: []const u8,
    blobs_url: []const u8,
    name: []const u8,
    forks_count: i64,
    has_issues: bool,
    watchers_count: i64,
    visibility: ?[]const u8 = null,
    comments_url: []const u8,
    default_branch: []const u8,
    stargazers_url: []const u8,
    mirror_url: ?[]const u8,
    starred_at: ?[]const u8 = null,
    watchers: i64,
    has_pages: bool,
    node_id: []const u8,
    has_discussions: ?bool = null,
    has_downloads: bool,
    archived: bool,
    web_commit_signoff_required: ?bool = null,
    subscription_url: []const u8,
    clone_url: []const u8,
    language: ?[]const u8,
    merge_commit_message: ?[]const u8 = null,
    allow_merge_commit: ?bool = null,
    contents_url: []const u8,
    pulls_url: []const u8,
    archive_url: []const u8,
    full_name: []const u8,
    notifications_url: []const u8,
    open_issues: i64,
    ssh_url: []const u8,
    html_url: []const u8,
    milestones_url: []const u8,
    open_issues_count: i64,
    git_refs_url: []const u8,
    merges_url: []const u8,
    compare_url: []const u8,
    private: bool,
    forks_url: []const u8,
    url: []const u8,
    issue_comment_url: []const u8,
    topics: ?[]const []const u8 = null,
    fork: bool,
    statuses_url: []const u8,
    has_pull_requests: ?bool = null,
    temp_clone_token: ?[]const u8 = null,
    allow_squash_merge: ?bool = null,
    delete_branch_on_merge: ?bool = null,
    merge_commit_title: ?[]const u8 = null,
    id: i64,
    allow_forking: ?bool = null,
    forks: i64,
    languages_url: []const u8,
    subscribers_url: []const u8,
    homepage: ?[]const u8,
    has_projects: bool,
    pushed_at: ?[]const u8,
    squash_merge_commit_title: ?[]const u8 = null,
    description: ?[]const u8,
    git_tags_url: []const u8,
    svn_url: []const u8,
    git_url: []const u8,
    downloads_url: []const u8,
    trees_url: []const u8,
    tags_url: []const u8,
    created_at: ?[]const u8,
    use_squash_pr_title_as_default: ?bool = null,
    license: @"nullable-license-simple",
    anonymous_access_enabled: ?bool = null,
    permissions: ?RepositoryPermissions = null,
    master_branch: ?[]const u8 = null,
    owner: @"simple-user",
    squash_merge_commit_message: ?[]const u8 = null,
    contributors_url: []const u8,
    git_commits_url: []const u8,
    events_url: []const u8,
    issues_url: []const u8,
    hooks_url: []const u8,
    keys_url: []const u8,
    is_template: ?bool = null,
    allow_rebase_merge: ?bool = null,
    updated_at: ?[]const u8,
    releases_url: []const u8,
    branches_url: []const u8,
    size: i64,
    labels_url: []const u8,
    disabled: bool,
    issue_events_url: []const u8,
    allow_auto_merge: ?bool = null,
    stargazers_count: i64,
    allow_update_branch: ?bool = null,
    teams_url: []const u8,
    commits_url: []const u8,
    collaborators_url: []const u8,
    code_search_index_status: ?RepositoryCodeSearchIndexStatus = null,
};

pub const HookDeliveryRequest = struct {
    payload: ?std.json.Value,
    headers: ?std.json.Value,
};

pub const HookDeliveryResponse = struct {
    payload: ?[]const u8,
    headers: ?std.json.Value,
};

pub const @"hook-delivery" = struct {
    repository_id: ?i64,
    url: ?[]const u8 = null,
    delivered_at: []const u8,
    request: HookDeliveryRequest,
    response: HookDeliveryResponse,
    status: []const u8,
    action: ?[]const u8,
    id: i64,
    status_code: i64,
    throttled_at: ?[]const u8 = null,
    guid: []const u8,
    duration: f64,
    redelivery: bool,
    event: []const u8,
    installation_id: ?i64,
};

pub const BranchProtectionBlockCreations = struct {
    enabled: ?bool = null,
};

pub const BranchProtectionLockBranch = struct {
    enabled: ?bool = null,
};

pub const BranchProtectionAllowForcePushes = struct {
    enabled: ?bool = null,
};

pub const BranchProtectionAllowForkSyncing = struct {
    enabled: ?bool = null,
};

pub const BranchProtectionRequiredLinearHistory = struct {
    enabled: ?bool = null,
};

pub const BranchProtectionAllowDeletions = struct {
    enabled: ?bool = null,
};

pub const BranchProtectionRequiredConversationResolution = struct {
    enabled: ?bool = null,
};

pub const BranchProtectionRequiredSignatures = struct {
    url: []const u8,
    enabled: bool,
};

pub const @"branch-protection" = struct {
    block_creations: ?BranchProtectionBlockCreations = null,
    url: ?[]const u8 = null,
    lock_branch: ?BranchProtectionLockBranch = null,
    required_pull_request_reviews: ?@"protected-branch-pull-request-review" = null,
    restrictions: ?@"branch-restriction-policy" = null,
    allow_force_pushes: ?BranchProtectionAllowForcePushes = null,
    protection_url: ?[]const u8 = null,
    allow_fork_syncing: ?BranchProtectionAllowForkSyncing = null,
    required_status_checks: ?@"protected-branch-required-status-check" = null,
    enforce_admins: ?@"protected-branch-admin-enforced" = null,
    required_linear_history: ?BranchProtectionRequiredLinearHistory = null,
    enabled: ?bool = null,
    name: ?[]const u8 = null,
    allow_deletions: ?BranchProtectionAllowDeletions = null,
    required_conversation_resolution: ?BranchProtectionRequiredConversationResolution = null,
    required_signatures: ?BranchProtectionRequiredSignatures = null,
};

pub const PullRequestReviewLinksPullRequest = struct {
    href: []const u8,
};

pub const PullRequestReviewLinksHtml = struct {
    href: []const u8,
};

pub const PullRequestReviewLinks = struct {
    pull_request: PullRequestReviewLinksPullRequest,
    html: PullRequestReviewLinksHtml,
};

pub const @"pull-request-review" = struct {
    pull_request_url: []const u8,
    state: []const u8,
    body_html: ?[]const u8 = null,
    commit_id: ?[]const u8,
    body_text: ?[]const u8 = null,
    id: i64,
    user: @"nullable-simple-user",
    _links: PullRequestReviewLinks,
    html_url: []const u8,
    node_id: []const u8,
    author_association: []const u8,
    submitted_at: ?[]const u8 = null,
    body: []const u8,
};

pub const @"webhook-config-content-type" = []const u8;

pub const @"pull-request-merge-async-result" = struct {
    status: []const u8,
    details: std.json.Value,
};

pub const BranchShortCommit = struct {
    sha: []const u8,
    url: []const u8,
};

pub const @"branch-short" = struct {
    commit: BranchShortCommit,
    name: []const u8,
    protected: bool,
};

pub const @"issue-event-rename" = struct {
    from: []const u8,
    to: []const u8,
};

pub const @"org-rules" = union(enum) {
    null,
    bool: bool,
    integer: i64,
    float: f64,
    number_string: []const u8,
    string: []const u8,
    array: std.json.Array,
    object: std.json.ObjectMap,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(_: std.mem.Allocator, source: std.json.Value, _: std.json.ParseOptions) !@This() {
        return switch (source) {
            .null => .null,
            .bool => |value| .{ .bool = value },
            .integer => |value| .{ .integer = value },
            .float => |value| .{ .float = value },
            .number_string => |value| .{ .number_string = value },
            .string => |value| .{ .string = value },
            .array => |value| .{ .array = value },
            .object => |value| .{ .object = value },
        };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .null => try jw.write(null),
            .bool => |value| try jw.write(value),
            .integer => |value| try jw.write(value),
            .float => |value| try jw.write(value),
            .number_string => |value| try jw.print("{s}", .{value}),
            .string => |value| try jw.write(value),
            .array => |value| try jw.write(value.items),
            .object => |value| {
                try jw.beginObject();
                var iterator = value.iterator();
                while (iterator.next()) |entry| {
                    try jw.objectField(entry.key_ptr.*);
                    try jw.write(entry.value_ptr.*);
                }
                try jw.endObject();
            },
        }
    }
};

pub const @"org-ruleset-conditions" = union(enum) {
    null,
    bool: bool,
    integer: i64,
    float: f64,
    number_string: []const u8,
    string: []const u8,
    array: std.json.Array,
    object: std.json.ObjectMap,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(_: std.mem.Allocator, source: std.json.Value, _: std.json.ParseOptions) !@This() {
        return switch (source) {
            .null => .null,
            .bool => |value| .{ .bool = value },
            .integer => |value| .{ .integer = value },
            .float => |value| .{ .float = value },
            .number_string => |value| .{ .number_string = value },
            .string => |value| .{ .string = value },
            .array => |value| .{ .array = value },
            .object => |value| .{ .object = value },
        };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .null => try jw.write(null),
            .bool => |value| try jw.write(value),
            .integer => |value| try jw.write(value),
            .float => |value| try jw.write(value),
            .number_string => |value| try jw.print("{s}", .{value}),
            .string => |value| try jw.write(value),
            .array => |value| try jw.write(value.items),
            .object => |value| {
                try jw.beginObject();
                var iterator = value.iterator();
                while (iterator.next()) |entry| {
                    try jw.objectField(entry.key_ptr.*);
                    try jw.write(entry.value_ptr.*);
                }
                try jw.endObject();
            },
        }
    }
};

pub const @"issue-comment" = struct {
    created_at: []const u8,
    url: []const u8,
    issue_url: []const u8,
    body_html: ?[]const u8 = null,
    body_text: ?[]const u8 = null,
    performed_via_github_app: ?@"nullable-integration" = null,
    id: i64,
    user: @"nullable-simple-user",
    updated_at: []const u8,
    reactions: ?@"reaction-rollup" = null,
    html_url: []const u8,
    node_id: []const u8,
    author_association: ?[]const u8 = null,
    pin: ?@"nullable-pinned-issue-comment" = null,
    body: ?[]const u8 = null,
    minimized: ?@"nullable-issue-comment-minimized" = null,
};

pub const FullRepositoryPermissions = struct {
    push: bool,
    admin: bool,
    maintain: ?bool = null,
    triage: ?bool = null,
    pull: bool,
};

pub const @"full-repository" = struct {
    has_issues: bool,
    comments_url: []const u8,
    default_branch: []const u8,
    stargazers_url: []const u8,
    watchers: i64,
    merge_commit_message: ?[]const u8 = null,
    subscription_url: []const u8,
    allow_merge_commit: ?bool = null,
    custom_properties: ?std.json.Value = null,
    subscribers_count: i64,
    full_name: []const u8,
    open_issues: i64,
    milestones_url: []const u8,
    open_issues_count: i64,
    merges_url: []const u8,
    allow_forking: ?bool = null,
    forks_url: []const u8,
    issue_comment_url: []const u8,
    network_count: i64,
    fork: bool,
    has_pull_requests: ?bool = null,
    code_of_conduct: ?@"code-of-conduct-simple" = null,
    languages_url: []const u8,
    homepage: ?[]const u8,
    pushed_at: []const u8,
    source: ?repository = null,
    git_tags_url: []const u8,
    downloads_url: []const u8,
    tags_url: []const u8,
    use_squash_pr_title_as_default: ?bool = null,
    license: @"nullable-license-simple",
    anonymous_access_enabled: ?bool = null,
    contributors_url: []const u8,
    master_branch: ?[]const u8 = null,
    git_commits_url: []const u8,
    owner: @"simple-user",
    hooks_url: []const u8,
    permissions: ?FullRepositoryPermissions = null,
    events_url: []const u8,
    keys_url: []const u8,
    allow_auto_merge: ?bool = null,
    releases_url: []const u8,
    size: i64,
    allow_update_branch: ?bool = null,
    stargazers_count: i64,
    collaborators_url: []const u8,
    name: []const u8,
    visibility: ?[]const u8 = null,
    pull_request_creation_policy: ?[]const u8 = null,
    has_wiki: bool,
    assignees_url: []const u8,
    blobs_url: []const u8,
    forks_count: i64,
    security_and_analysis: ?@"security-and-analysis" = null,
    mirror_url: ?[]const u8,
    has_pages: bool,
    node_id: []const u8,
    has_discussions: bool,
    has_downloads: ?bool = null,
    archived: bool,
    web_commit_signoff_required: ?bool = null,
    language: ?[]const u8,
    clone_url: []const u8,
    contents_url: []const u8,
    pulls_url: []const u8,
    archive_url: []const u8,
    notifications_url: []const u8,
    ssh_url: []const u8,
    html_url: []const u8,
    parent: ?repository = null,
    git_refs_url: []const u8,
    compare_url: []const u8,
    private: bool,
    topics: ?[]const []const u8 = null,
    url: []const u8,
    allow_squash_merge: ?bool = null,
    delete_branch_on_merge: ?bool = null,
    merge_commit_title: ?[]const u8 = null,
    statuses_url: []const u8,
    organization: ?@"nullable-simple-user" = null,
    temp_clone_token: ?[]const u8 = null,
    id: i64,
    forks: i64,
    subscribers_url: []const u8,
    template_repository: ?@"nullable-repository" = null,
    has_projects: bool,
    squash_merge_commit_title: ?[]const u8 = null,
    description: ?[]const u8,
    svn_url: []const u8,
    git_url: []const u8,
    trees_url: []const u8,
    created_at: []const u8,
    squash_merge_commit_message: ?[]const u8 = null,
    issues_url: []const u8,
    allow_rebase_merge: ?bool = null,
    is_template: ?bool = null,
    updated_at: []const u8,
    branches_url: []const u8,
    disabled: bool,
    labels_url: []const u8,
    issue_events_url: []const u8,
    teams_url: []const u8,
    commits_url: []const u8,
    deployments_url: []const u8,
    watchers_count: i64,
};

pub const @"issue-suggestion" = struct {
    created_at: []const u8,
    target_value: ?std.json.Value,
    actor_id: ?i64,
    state: []const u8,
    confidence: ?[]const u8,
    action: []const u8,
    id: i64,
    issue_event_id: ?i64,
    resolved_by: ?i64,
    updated_at: []const u8,
    rationale: ?[]const u8,
    target_id: ?i64,
    issue_id: i64,
};

pub const @"empty-object" = union(enum) {
    null,
    bool: bool,
    integer: i64,
    float: f64,
    number_string: []const u8,
    string: []const u8,
    array: std.json.Array,
    object: std.json.ObjectMap,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(_: std.mem.Allocator, source: std.json.Value, _: std.json.ParseOptions) !@This() {
        return switch (source) {
            .null => .null,
            .bool => |value| .{ .bool = value },
            .integer => |value| .{ .integer = value },
            .float => |value| .{ .float = value },
            .number_string => |value| .{ .number_string = value },
            .string => |value| .{ .string = value },
            .array => |value| .{ .array = value },
            .object => |value| .{ .object = value },
        };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .null => try jw.write(null),
            .bool => |value| try jw.write(value),
            .integer => |value| try jw.write(value),
            .float => |value| try jw.write(value),
            .number_string => |value| try jw.print("{s}", .{value}),
            .string => |value| try jw.write(value),
            .array => |value| try jw.write(value.items),
            .object => |value| {
                try jw.beginObject();
                var iterator = value.iterator();
                while (iterator.next()) |entry| {
                    try jw.objectField(entry.key_ptr.*);
                    try jw.write(entry.value_ptr.*);
                }
                try jw.endObject();
            },
        }
    }
};

pub const @"issue-event-project-card" = struct {
    column_name: []const u8,
    project_id: i64,
    url: []const u8,
    id: i64,
    previous_column_name: ?[]const u8 = null,
    project_url: []const u8,
};

pub const @"deployment-protection-rule" = struct {
    app: @"custom-deployment-rule-app",
    id: i64,
    node_id: []const u8,
    enabled: bool,
};

pub const label = struct {
    default: bool,
    url: []const u8,
    color: []const u8,
    node_id: []const u8,
    description: ?[]const u8,
    id: i64,
    name: []const u8,
};

pub const @"code-frequency-stat" = []const i64;

pub const @"protected-branch-admin-enforced" = struct {
    url: []const u8,
    enabled: bool,
};

pub const @"view-traffic" = struct {
    uniques: i64,
    views: []const traffic,
    count: i64,
};

pub const RepositoryRulesetLinksSelf = struct {
    href: ?[]const u8 = null,
};

pub const RepositoryRulesetLinksHtml = struct {
    href: ?[]const u8 = null,
};

pub const RepositoryRulesetLinks = struct {
    self: ?RepositoryRulesetLinksSelf = null,
    html: ?RepositoryRulesetLinksHtml = null,
};

pub const @"repository-ruleset" = struct {
    created_at: ?[]const u8 = null,
    current_user_can_bypass: ?[]const u8 = null,
    target: ?[]const u8 = null,
    bypass_actors: ?[]const @"repository-ruleset-bypass-actor" = null,
    id: i64,
    updated_at: ?[]const u8 = null,
    _links: ?RepositoryRulesetLinks = null,
    conditions: ?std.json.Value = null,
    enforcement: []const u8,
    node_id: ?[]const u8 = null,
    rules: ?[]const @"repository-rule" = null,
    source: []const u8,
    name: []const u8,
    source_type: ?[]const u8 = null,
};

pub const @"webhook-config-insecure-ssl" = std.json.Value;

pub const @"nullable-simple-user" = struct {
    url: []const u8,
    subscriptions_url: []const u8,
    organizations_url: []const u8,
    email: ?[]const u8 = null,
    login: []const u8,
    gists_url: []const u8,
    events_url: []const u8,
    gravatar_id: ?[]const u8,
    id: i64,
    repos_url: []const u8,
    followers_url: []const u8,
    starred_url: []const u8,
    starred_at: ?[]const u8 = null,
    html_url: []const u8,
    node_id: []const u8,
    site_admin: bool,
    user_view_type: ?[]const u8 = null,
    following_url: []const u8,
    avatar_url: []const u8,
    name: ?[]const u8 = null,
    received_events_url: []const u8,
    type: []const u8,
};

pub const @"hook-delivery-item" = struct {
    repository_id: ?i64,
    guid: []const u8,
    duration: f64,
    delivered_at: []const u8,
    redelivery: bool,
    status: []const u8,
    event: []const u8,
    action: ?[]const u8,
    id: i64,
    status_code: i64,
    installation_id: ?i64,
    throttled_at: ?[]const u8 = null,
};

pub const @"clone-traffic" = struct {
    uniques: i64,
    clones: []const traffic,
    count: i64,
};

pub const @"nullable-milestone" = struct {
    created_at: []const u8,
    url: []const u8,
    state: []const u8,
    id: i64,
    creator: @"nullable-simple-user",
    due_on: ?[]const u8,
    updated_at: []const u8,
    number: i64,
    open_issues: i64,
    labels_url: []const u8,
    html_url: []const u8,
    node_id: []const u8,
    description: ?[]const u8,
    closed_at: ?[]const u8,
    title: []const u8,
    closed_issues: i64,
};

pub const @"issue-event-dismissed-review" = struct {
    state: []const u8,
    dismissal_message: ?[]const u8,
    review_id: i64,
    dismissal_commit_id: ?[]const u8 = null,
};

pub const @"deployment-branch-policy-settings" = struct {
    protected_branches: bool,
    custom_branch_policies: bool,
};

pub const @"pull-request-review-request" = struct {
    users: []const @"simple-user",
    teams: []const team,
};

pub const PullRequestReviewCommentLinksSelf = struct {
    href: []const u8,
};

pub const PullRequestReviewCommentLinksPullRequest = struct {
    href: []const u8,
};

pub const PullRequestReviewCommentLinksHtml = struct {
    href: []const u8,
};

pub const PullRequestReviewCommentLinks = struct {
    self: PullRequestReviewCommentLinksSelf,
    pull_request: PullRequestReviewCommentLinksPullRequest,
    html: PullRequestReviewCommentLinksHtml,
};

pub const @"pull-request-review-comment" = struct {
    pull_request_url: []const u8,
    original_position: ?i64 = null,
    url: []const u8,
    position: ?i64 = null,
    body_html: ?[]const u8 = null,
    in_reply_to_id: ?i64 = null,
    id: i64,
    original_start_line: ?i64 = null,
    _links: PullRequestReviewCommentLinks,
    reactions: ?@"reaction-rollup" = null,
    subject_type: ?[]const u8 = null,
    node_id: []const u8,
    diff_hunk: []const u8,
    start_line: ?i64 = null,
    side: ?[]const u8 = null,
    original_commit_id: []const u8,
    body: []const u8,
    created_at: []const u8,
    start_side: ?[]const u8 = null,
    commit_id: []const u8,
    line: ?i64 = null,
    body_text: ?[]const u8 = null,
    user: @"nullable-simple-user",
    pull_request_review_id: ?i64,
    updated_at: []const u8,
    html_url: []const u8,
    author_association: []const u8,
    path: []const u8,
    original_line: ?i64 = null,
};

pub const @"nullable-issue-comment-minimized" = struct {
    reason: ?[]const u8,
};

pub const @"author-association" = []const u8;

pub const RulesetVersionActor = struct {
    id: ?i64 = null,
    type: ?[]const u8 = null,
};

pub const @"ruleset-version" = struct {
    actor: RulesetVersionActor,
    version_id: i64,
    updated_at: []const u8,
};

pub const @"check-automated-security-fixes" = struct {
    paused: bool,
    enabled: bool,
};

pub const ContentFileLinks = struct {
    self: []const u8,
    git: ?[]const u8,
    html: ?[]const u8,
};

pub const @"content-file" = struct {
    encoding: []const u8,
    url: []const u8,
    target: ?[]const u8 = null,
    download_url: ?[]const u8,
    content: []const u8,
    size: i64,
    _links: ContentFileLinks,
    html_url: ?[]const u8,
    submodule_git_url: ?[]const u8 = null,
    sha: []const u8,
    path: []const u8,
    name: []const u8,
    type: []const u8,
    git_url: ?[]const u8,
};

pub const PullRequestStackBase = struct {
    sha: []const u8,
    ref: []const u8,
};

pub const @"pull-request-stack" = struct {
    size: ?i64 = null,
    position: ?i64 = null,
    id: ?i64 = null,
    base: PullRequestStackBase,
    number: ?i64 = null,
};

pub const ContributorActivityWeeksItem = struct {
    a: ?i64 = null,
    c: ?i64 = null,
    w: ?i64 = null,
    d: ?i64 = null,
};

pub const @"contributor-activity" = struct {
    author: @"nullable-simple-user",
    total: i64,
    weeks: []const ContributorActivityWeeksItem,
};

pub const @"pull-request-merge-result" = struct {
    sha: []const u8,
    merged: bool,
    message: []const u8,
};

pub const NullableIntegrationPermissions = struct {
    issues: ?[]const u8 = null,
    checks: ?[]const u8 = null,
    metadata: ?[]const u8 = null,
    deployments: ?[]const u8 = null,
    contents: ?[]const u8 = null,
};

pub const @"nullable-integration" = struct {
    created_at: []const u8,
    client_id: ?[]const u8 = null,
    owner: std.json.Value,
    permissions: NullableIntegrationPermissions,
    events: []const []const u8,
    id: i64,
    updated_at: []const u8,
    html_url: []const u8,
    node_id: []const u8,
    installations_count: ?i64 = null,
    description: ?[]const u8,
    name: []const u8,
    external_url: []const u8,
    slug: ?[]const u8 = null,
};

pub const PageBuildError = struct {
    message: ?[]const u8,
};

pub const @"page-build" = struct {
    @"error": PageBuildError,
    created_at: []const u8,
    url: []const u8,
    duration: i64,
    pusher: @"nullable-simple-user",
    status: []const u8,
    commit: []const u8,
    updated_at: []const u8,
};

pub const @"nullable-code-of-conduct-simple" = struct {
    url: []const u8,
    key: []const u8,
    name: []const u8,
    html_url: ?[]const u8,
};

pub const @"deployment-branch-policy-name-pattern" = struct {
    name: []const u8,
};

pub const milestone = struct {
    created_at: []const u8,
    url: []const u8,
    state: []const u8,
    id: i64,
    creator: @"nullable-simple-user",
    due_on: ?[]const u8,
    updated_at: []const u8,
    number: i64,
    open_issues: i64,
    labels_url: []const u8,
    html_url: []const u8,
    node_id: []const u8,
    description: ?[]const u8,
    closed_at: ?[]const u8,
    title: []const u8,
    closed_issues: i64,
};

pub const @"repository-collaborator-permission" = struct {
    permission: []const u8,
    role_name: []const u8,
    user: @"nullable-collaborator",
};

pub const @"issue-event" = struct {
    url: []const u8,
    assignee: ?@"nullable-simple-user" = null,
    rename: ?@"issue-event-rename" = null,
    id: i64,
    requested_reviewer: ?@"nullable-simple-user" = null,
    requested_team: ?team = null,
    blocked_by: ?@"nullable-issue-reference" = null,
    node_id: []const u8,
    parent_issue: ?@"nullable-issue-reference" = null,
    assigner: ?@"nullable-simple-user" = null,
    lock_reason: ?[]const u8 = null,
    commit_url: ?[]const u8,
    event: []const u8,
    issue: ?@"nullable-issue" = null,
    review_requester: ?@"nullable-simple-user" = null,
    blocking: ?@"nullable-issue-reference" = null,
    created_at: []const u8,
    dismissed_review: ?@"issue-event-dismissed-review" = null,
    sub_issue: ?@"nullable-issue-reference" = null,
    commit_id: ?[]const u8,
    milestone: ?@"issue-event-milestone" = null,
    actor: @"nullable-simple-user",
    performed_via_github_app: ?@"nullable-integration" = null,
    issue_type: ?@"issue-type-webhook" = null,
    project_card: ?@"issue-event-project-card" = null,
    intent: ?@"nullable-issue-event-intent" = null,
    author_association: ?[]const u8 = null,
    prev_issue_type: ?@"issue-type-webhook" = null,
    label: ?@"issue-event-label" = null,
};

pub const ReviewCommentLinks = struct {
    self: link,
    pull_request: link,
    html: link,
};

pub const @"review-comment" = struct {
    pull_request_url: []const u8,
    original_position: i64,
    url: []const u8,
    position: ?i64,
    body_html: ?[]const u8 = null,
    in_reply_to_id: ?i64 = null,
    id: i64,
    original_start_line: ?i64 = null,
    _links: ReviewCommentLinks,
    reactions: ?@"reaction-rollup" = null,
    subject_type: ?[]const u8 = null,
    node_id: []const u8,
    diff_hunk: []const u8,
    start_line: ?i64 = null,
    original_commit_id: []const u8,
    body: []const u8,
    side: ?[]const u8 = null,
    created_at: []const u8,
    start_side: ?[]const u8 = null,
    commit_id: []const u8,
    body_text: ?[]const u8 = null,
    line: ?i64 = null,
    user: @"nullable-simple-user",
    pull_request_review_id: ?i64,
    updated_at: []const u8,
    html_url: []const u8,
    author_association: []const u8,
    path: []const u8,
    original_line: ?i64 = null,
};

pub const @"commit-activity" = struct {
    total: i64,
    days: []const i64,
    week: i64,
};

pub const MinimalRepositoryPermissions = struct {
    push: ?bool = null,
    admin: ?bool = null,
    maintain: ?bool = null,
    triage: ?bool = null,
    pull: ?bool = null,
};

pub const MinimalRepositoryLicense = struct {
    url: ?[]const u8 = null,
    key: ?[]const u8 = null,
    name: ?[]const u8 = null,
    spdx_id: ?[]const u8 = null,
    node_id: ?[]const u8 = null,
};

pub const @"minimal-repository" = struct {
    pull_request_creation_policy: ?[]const u8 = null,
    has_wiki: ?bool = null,
    assignees_url: []const u8,
    blobs_url: []const u8,
    forks_count: ?i64 = null,
    has_issues: ?bool = null,
    comments_url: []const u8,
    default_branch: ?[]const u8 = null,
    role_name: ?[]const u8 = null,
    security_and_analysis: ?@"security-and-analysis" = null,
    mirror_url: ?[]const u8 = null,
    stargazers_url: []const u8,
    watchers: ?i64 = null,
    has_pages: ?bool = null,
    node_id: []const u8,
    has_discussions: ?bool = null,
    has_downloads: ?bool = null,
    archived: ?bool = null,
    web_commit_signoff_required: ?bool = null,
    subscription_url: []const u8,
    clone_url: ?[]const u8 = null,
    language: ?[]const u8 = null,
    contents_url: []const u8,
    pulls_url: []const u8,
    custom_properties: ?std.json.Value = null,
    archive_url: []const u8,
    subscribers_count: ?i64 = null,
    full_name: []const u8,
    notifications_url: []const u8,
    open_issues: ?i64 = null,
    ssh_url: ?[]const u8 = null,
    html_url: []const u8,
    milestones_url: []const u8,
    open_issues_count: ?i64 = null,
    git_refs_url: []const u8,
    merges_url: []const u8,
    allow_forking: ?bool = null,
    private: bool,
    forks_url: []const u8,
    url: []const u8,
    issue_comment_url: []const u8,
    topics: ?[]const []const u8 = null,
    fork: bool,
    statuses_url: []const u8,
    has_pull_requests: ?bool = null,
    temp_clone_token: ?[]const u8 = null,
    delete_branch_on_merge: ?bool = null,
    network_count: ?i64 = null,
    code_of_conduct: ?@"code-of-conduct" = null,
    id: i64,
    compare_url: []const u8,
    forks: ?i64 = null,
    languages_url: []const u8,
    subscribers_url: []const u8,
    homepage: ?[]const u8 = null,
    has_projects: ?bool = null,
    pushed_at: ?[]const u8 = null,
    description: ?[]const u8,
    git_tags_url: []const u8,
    svn_url: ?[]const u8 = null,
    git_url: ?[]const u8 = null,
    downloads_url: []const u8,
    trees_url: []const u8,
    tags_url: []const u8,
    created_at: ?[]const u8 = null,
    contributors_url: []const u8,
    git_commits_url: []const u8,
    owner: @"simple-user",
    hooks_url: []const u8,
    permissions: ?MinimalRepositoryPermissions = null,
    events_url: []const u8,
    issues_url: []const u8,
    license: ?MinimalRepositoryLicense = null,
    keys_url: []const u8,
    is_template: ?bool = null,
    updated_at: ?[]const u8 = null,
    releases_url: []const u8,
    branches_url: []const u8,
    size: ?i64 = null,
    labels_url: []const u8,
    disabled: ?bool = null,
    issue_events_url: []const u8,
    stargazers_count: ?i64 = null,
    teams_url: []const u8,
    commits_url: []const u8,
    collaborators_url: []const u8,
    deployments_url: []const u8,
    name: []const u8,
    watchers_count: ?i64 = null,
    visibility: ?[]const u8 = null,
};

pub const @"nullable-git-user" = struct {
    date: ?[]const u8 = null,
    name: ?[]const u8 = null,
    email: ?[]const u8 = null,
};

pub const @"nullable-community-health-file" = struct {
    url: []const u8,
    html_url: []const u8,
};

pub const @"issue-type-webhook" = struct {
    color: ?[]const u8 = null,
    id: i64,
    name: []const u8,
};

pub const @"repository-invitation" = struct {
    repository: @"minimal-repository",
    created_at: []const u8,
    inviter: @"nullable-simple-user",
    url: []const u8,
    html_url: []const u8,
    permissions: []const u8,
    node_id: []const u8,
    id: i64,
    invitee: @"nullable-simple-user",
    expired: ?bool = null,
};

pub const @"webhook-config-secret" = []const u8;

pub const @"nullable-issue-event-intent" = struct {
    rationale: ?[]const u8 = null,
    confidence: ?[]const u8 = null,
};

pub const SecurityAndAnalysisSecretScanningDelegatedAlertDismissal = struct {
    status: ?[]const u8 = null,
};

pub const SecurityAndAnalysisAdvancedSecurity = struct {
    status: ?[]const u8 = null,
};

pub const SecurityAndAnalysisSecretScanningAiDetection = struct {
    status: ?[]const u8 = null,
};

pub const SecurityAndAnalysisSecretScanningNonProviderPatterns = struct {
    status: ?[]const u8 = null,
};

pub const SecurityAndAnalysisSecretScanningDelegatedBypass = struct {
    status: ?[]const u8 = null,
};

pub const SecurityAndAnalysisSecretScanning = struct {
    status: ?[]const u8 = null,
};

pub const SecurityAndAnalysisDependabotSecurityUpdates = struct {
    status: ?[]const u8 = null,
};

pub const SecurityAndAnalysisCodeSecurity = struct {
    status: ?[]const u8 = null,
};

pub const SecurityAndAnalysisSecretScanningPushProtection = struct {
    status: ?[]const u8 = null,
};

pub const SecurityAndAnalysisSecretScanningDelegatedBypassOptionsReviewersItem = struct {
    reviewer_type: []const u8,
    mode: ?[]const u8 = null,
    reviewer_id: i64,
};

pub const SecurityAndAnalysisSecretScanningDelegatedBypassOptions = struct {
    reviewers: ?[]const SecurityAndAnalysisSecretScanningDelegatedBypassOptionsReviewersItem = null,
};

pub const @"security-and-analysis" = struct {
    secret_scanning_delegated_alert_dismissal: ?SecurityAndAnalysisSecretScanningDelegatedAlertDismissal = null,
    advanced_security: ?SecurityAndAnalysisAdvancedSecurity = null,
    secret_scanning_ai_detection: ?SecurityAndAnalysisSecretScanningAiDetection = null,
    secret_scanning_non_provider_patterns: ?SecurityAndAnalysisSecretScanningNonProviderPatterns = null,
    secret_scanning_delegated_bypass: ?SecurityAndAnalysisSecretScanningDelegatedBypass = null,
    secret_scanning: ?SecurityAndAnalysisSecretScanning = null,
    dependabot_security_updates: ?SecurityAndAnalysisDependabotSecurityUpdates = null,
    code_security: ?SecurityAndAnalysisCodeSecurity = null,
    secret_scanning_push_protection: ?SecurityAndAnalysisSecretScanningPushProtection = null,
    secret_scanning_delegated_bypass_options: ?SecurityAndAnalysisSecretScanningDelegatedBypassOptions = null,
};

pub const CodeownersErrorsErrorsItem = struct {
    column: i64,
    kind: []const u8,
    source: ?[]const u8 = null,
    line: i64,
    path: []const u8,
    suggestion: ?[]const u8 = null,
    message: []const u8,
};

pub const @"codeowners-errors" = struct {
    errors: []const CodeownersErrorsErrorsItem,
};

pub const topic = struct {
    names: []const []const u8,
};

pub const @"issue-type" = struct {
    created_at: ?[]const u8 = null,
    color: ?[]const u8 = null,
    node_id: []const u8,
    is_enabled: ?bool = null,
    description: ?[]const u8,
    id: i64,
    name: []const u8,
    updated_at: ?[]const u8 = null,
};

pub const @"repository-ruleset-bypass-actor" = struct {
    actor_type: []const u8,
    actor_id: ?i64 = null,
    bypass_mode: ?[]const u8 = null,
};

pub const environment = struct {
    created_at: []const u8,
    protection_rules: ?[]const std.json.Value = null,
    url: []const u8,
    deployment_branch_policy: ?@"deployment-branch-policy-settings" = null,
    html_url: []const u8,
    node_id: []const u8,
    id: i64,
    name: []const u8,
    updated_at: []const u8,
};

pub const verification = struct {
    payload: ?[]const u8,
    verified: bool,
    reason: []const u8,
    signature: ?[]const u8,
    verified_at: ?[]const u8,
};

pub const @"repository-hash-algorithm" = struct {
    hash_algorithm: []const u8,
};

pub const IssueFieldValueSingleSelectOption = struct {
    color: []const u8,
    id: i64,
    name: []const u8,
};

pub const IssueFieldValueMultiSelectOptionsItem = struct {
    color: []const u8,
    id: i64,
    name: []const u8,
};

pub const @"issue-field-value" = struct {
    issue_field_name: ?[]const u8 = null,
    single_select_option: ?IssueFieldValueSingleSelectOption = null,
    node_id: []const u8,
    issue_field_id: i64,
    value: ?std.json.Value,
    multi_select_options: ?[]const IssueFieldValueMultiSelectOptionsItem = null,
    data_type: []const u8,
};

pub const @"timeline-issue-events" = union(enum) {
    null,
    bool: bool,
    integer: i64,
    float: f64,
    number_string: []const u8,
    string: []const u8,
    array: std.json.Array,
    object: std.json.ObjectMap,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(_: std.mem.Allocator, source: std.json.Value, _: std.json.ParseOptions) !@This() {
        return switch (source) {
            .null => .null,
            .bool => |value| .{ .bool = value },
            .integer => |value| .{ .integer = value },
            .float => |value| .{ .float = value },
            .number_string => |value| .{ .number_string = value },
            .string => |value| .{ .string = value },
            .array => |value| .{ .array = value },
            .object => |value| .{ .object = value },
        };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .null => try jw.write(null),
            .bool => |value| try jw.write(value),
            .integer => |value| try jw.write(value),
            .float => |value| try jw.write(value),
            .number_string => |value| try jw.print("{s}", .{value}),
            .string => |value| try jw.write(value),
            .array => |value| try jw.write(value.items),
            .object => |value| {
                try jw.beginObject();
                var iterator = value.iterator();
                while (iterator.next()) |entry| {
                    try jw.objectField(entry.key_ptr.*);
                    try jw.write(entry.value_ptr.*);
                }
                try jw.endObject();
            },
        }
    }
};

pub const contributor = struct {
    url: ?[]const u8 = null,
    contributions: i64,
    subscriptions_url: ?[]const u8 = null,
    organizations_url: ?[]const u8 = null,
    login: ?[]const u8 = null,
    gists_url: ?[]const u8 = null,
    events_url: ?[]const u8 = null,
    email: ?[]const u8 = null,
    gravatar_id: ?[]const u8 = null,
    id: ?i64 = null,
    repos_url: ?[]const u8 = null,
    followers_url: ?[]const u8 = null,
    starred_url: ?[]const u8 = null,
    html_url: ?[]const u8 = null,
    node_id: ?[]const u8 = null,
    site_admin: ?bool = null,
    user_view_type: ?[]const u8 = null,
    following_url: ?[]const u8 = null,
    avatar_url: ?[]const u8 = null,
    received_events_url: ?[]const u8 = null,
    type: []const u8,
    name: ?[]const u8 = null,
};

pub const PullRequestBase = struct {
    sha: []const u8,
    ref: []const u8,
    label: []const u8,
    repo: repository,
    user: @"simple-user",
};

pub const PullRequestLinks = struct {
    statuses: link,
    comments: link,
    review_comments: link,
    review_comment: link,
    html: link,
    self: link,
    issue: link,
    commits: link,
};

pub const PullRequestLabelsItem = struct {
    default: bool,
    url: []const u8,
    color: []const u8,
    node_id: []const u8,
    description: ?[]const u8,
    id: i64,
    name: []const u8,
};

pub const PullRequestHead = struct {
    sha: []const u8,
    ref: []const u8,
    label: []const u8,
    repo: repository,
    user: @"simple-user",
};

pub const @"pull-request" = struct {
    comments: i64,
    url: []const u8,
    review_comments: i64,
    statuses_url: []const u8,
    active_lock_reason: ?[]const u8 = null,
    assignee: @"nullable-simple-user",
    requested_teams: ?[]const @"team-simple" = null,
    merged: bool,
    comments_url: []const u8,
    id: i64,
    base: PullRequestBase,
    number: i64,
    _links: PullRequestLinks,
    deletions: i64,
    review_comment_url: []const u8,
    node_id: []const u8,
    changed_files: i64,
    mergeable: ?bool,
    merged_by: @"nullable-simple-user",
    mergeable_state: []const u8,
    body: ?[]const u8,
    commits: i64,
    draft: ?bool = null,
    review_comments_url: []const u8,
    created_at: []const u8,
    issue_url: []const u8,
    auto_merge: @"auto-merge",
    state: []const u8,
    assignees: ?[]const @"simple-user" = null,
    milestone: @"nullable-milestone",
    diff_url: []const u8,
    locked: bool,
    maintainer_can_modify: bool,
    user: @"simple-user",
    merge_commit_sha: ?[]const u8,
    updated_at: []const u8,
    patch_url: []const u8,
    requested_reviewers: ?[]const @"simple-user" = null,
    rebaseable: ?bool = null,
    labels: []const PullRequestLabelsItem,
    html_url: []const u8,
    head: PullRequestHead,
    author_association: []const u8,
    stack: ?@"pull-request-stack" = null,
    additions: i64,
    commits_url: []const u8,
    closed_at: ?[]const u8,
    merged_at: ?[]const u8,
    title: []const u8,
};

pub const @"participation-stats" = struct {
    owner: []const i64,
    all: []const i64,
};

pub const @"auto-merge" = struct {
    commit_message: []const u8,
    commit_title: []const u8,
    enabled_by: @"simple-user",
    merge_method: []const u8,
};

pub const activity = struct {
    timestamp: []const u8,
    node_id: []const u8,
    before: []const u8,
    after: []const u8,
    ref: []const u8,
    id: i64,
    activity_type: []const u8,
    actor: @"nullable-simple-user",
};

pub const NullableRepositoryPermissions = struct {
    push: bool,
    admin: bool,
    maintain: ?bool = null,
    triage: ?bool = null,
    pull: bool,
};

pub const NullableRepositoryCodeSearchIndexStatus = struct {
    lexical_search_ok: ?bool = null,
    lexical_commit_sha: ?[]const u8 = null,
};

pub const @"nullable-repository" = struct {
    deployments_url: []const u8,
    pull_request_creation_policy: ?[]const u8 = null,
    has_wiki: bool,
    assignees_url: []const u8,
    blobs_url: []const u8,
    name: []const u8,
    forks_count: i64,
    has_issues: bool,
    watchers_count: i64,
    visibility: ?[]const u8 = null,
    comments_url: []const u8,
    default_branch: []const u8,
    stargazers_url: []const u8,
    mirror_url: ?[]const u8,
    starred_at: ?[]const u8 = null,
    watchers: i64,
    has_pages: bool,
    node_id: []const u8,
    has_discussions: ?bool = null,
    has_downloads: bool,
    archived: bool,
    web_commit_signoff_required: ?bool = null,
    subscription_url: []const u8,
    clone_url: []const u8,
    language: ?[]const u8,
    merge_commit_message: ?[]const u8 = null,
    allow_merge_commit: ?bool = null,
    contents_url: []const u8,
    pulls_url: []const u8,
    archive_url: []const u8,
    full_name: []const u8,
    notifications_url: []const u8,
    open_issues: i64,
    ssh_url: []const u8,
    html_url: []const u8,
    milestones_url: []const u8,
    open_issues_count: i64,
    git_refs_url: []const u8,
    merges_url: []const u8,
    compare_url: []const u8,
    private: bool,
    forks_url: []const u8,
    url: []const u8,
    issue_comment_url: []const u8,
    topics: ?[]const []const u8 = null,
    fork: bool,
    statuses_url: []const u8,
    has_pull_requests: ?bool = null,
    temp_clone_token: ?[]const u8 = null,
    allow_squash_merge: ?bool = null,
    delete_branch_on_merge: ?bool = null,
    merge_commit_title: ?[]const u8 = null,
    id: i64,
    allow_forking: ?bool = null,
    forks: i64,
    languages_url: []const u8,
    subscribers_url: []const u8,
    homepage: ?[]const u8,
    has_projects: bool,
    pushed_at: ?[]const u8,
    squash_merge_commit_title: ?[]const u8 = null,
    description: ?[]const u8,
    git_tags_url: []const u8,
    svn_url: []const u8,
    git_url: []const u8,
    downloads_url: []const u8,
    trees_url: []const u8,
    tags_url: []const u8,
    created_at: ?[]const u8,
    use_squash_pr_title_as_default: ?bool = null,
    license: @"nullable-license-simple",
    anonymous_access_enabled: ?bool = null,
    permissions: ?NullableRepositoryPermissions = null,
    master_branch: ?[]const u8 = null,
    owner: @"simple-user",
    squash_merge_commit_message: ?[]const u8 = null,
    contributors_url: []const u8,
    git_commits_url: []const u8,
    events_url: []const u8,
    issues_url: []const u8,
    hooks_url: []const u8,
    keys_url: []const u8,
    is_template: ?bool = null,
    allow_rebase_merge: ?bool = null,
    updated_at: ?[]const u8,
    releases_url: []const u8,
    branches_url: []const u8,
    size: i64,
    labels_url: []const u8,
    disabled: bool,
    issue_events_url: []const u8,
    allow_auto_merge: ?bool = null,
    stargazers_count: i64,
    allow_update_branch: ?bool = null,
    teams_url: []const u8,
    commits_url: []const u8,
    collaborators_url: []const u8,
    code_search_index_status: ?NullableRepositoryCodeSearchIndexStatus = null,
};

pub const @"deployment-branch-policy-name-pattern-with-type" = struct {
    name: []const u8,
    type: ?[]const u8 = null,
};

pub const @"code-of-conduct" = struct {
    url: []const u8,
    key: []const u8,
    name: []const u8,
    body: ?[]const u8 = null,
    html_url: ?[]const u8,
};

pub const @"deployment-reviewer-type" = []const u8;

pub const @"sub-issues-summary" = struct {
    completed: i64,
    percent_completed: i64,
    total: i64,
};

pub const RuleSuiteRuleEvaluationsItemRuleSource = struct {
    id: ?i64 = null,
    type: ?[]const u8 = null,
    name: ?[]const u8 = null,
};

pub const RuleSuiteRuleEvaluationsItem = struct {
    details: ?[]const u8 = null,
    rule_source: ?RuleSuiteRuleEvaluationsItemRuleSource = null,
    rule_type: ?[]const u8 = null,
    result: ?[]const u8 = null,
    enforcement: ?[]const u8 = null,
};

pub const @"rule-suite" = struct {
    actor_name: ?[]const u8 = null,
    repository_id: ?i64 = null,
    actor_id: ?i64 = null,
    after_sha: ?[]const u8 = null,
    result: ?[]const u8 = null,
    before_sha: ?[]const u8 = null,
    repository_name: ?[]const u8 = null,
    pushed_at: ?[]const u8 = null,
    rule_evaluations: ?[]const RuleSuiteRuleEvaluationsItem = null,
    ref: ?[]const u8 = null,
    id: ?i64 = null,
    evaluation_result: ?[]const u8 = null,
};

pub const @"nullable-license-simple" = struct {
    node_id: []const u8,
    url: ?[]const u8,
    html_url: ?[]const u8 = null,
    key: []const u8,
    name: []const u8,
    spdx_id: ?[]const u8,
};

pub const @"custom-property-value" = struct {
    value: ?std.json.Value,
    property_name: []const u8,
};

pub const @"pages-deployment-status" = struct {
    status: ?[]const u8 = null,
};

pub const @"issue-event-label" = struct {
    color: ?[]const u8,
    name: ?[]const u8,
};

pub const ShortBranchCommit = struct {
    sha: []const u8,
    url: []const u8,
};

pub const @"short-branch" = struct {
    commit: ShortBranchCommit,
    name: []const u8,
    protected: bool,
    protection: ?@"branch-protection" = null,
    protection_url: ?[]const u8 = null,
};

pub const page = struct {
    custom_404: bool,
    url: []const u8,
    html_url: ?[]const u8 = null,
    protected_domain_state: ?[]const u8 = null,
    status: ?[]const u8,
    source: ?@"pages-source-hash" = null,
    https_enforced: ?bool = null,
    pending_domain_unverified_at: ?[]const u8 = null,
    build_type: ?[]const u8 = null,
    public: bool,
    cname: ?[]const u8,
    https_certificate: ?@"pages-https-certificate" = null,
};

pub const deployment = struct {
    created_at: []const u8,
    payload: std.json.Value,
    url: []const u8,
    statuses_url: []const u8,
    repository_url: []const u8,
    transient_environment: ?bool = null,
    original_environment: ?[]const u8 = null,
    ref: []const u8,
    id: i64,
    creator: @"nullable-simple-user",
    performed_via_github_app: ?@"nullable-integration" = null,
    updated_at: []const u8,
    environment: []const u8,
    node_id: []const u8,
    sha: []const u8,
    description: ?[]const u8,
    task: []const u8,
    production_environment: ?bool = null,
};

pub const release = struct {
    created_at: []const u8,
    url: []const u8,
    mentions_count: ?i64 = null,
    prerelease: bool,
    body_html: ?[]const u8 = null,
    tarball_url: ?[]const u8,
    published_at: ?[]const u8,
    body_text: ?[]const u8 = null,
    upload_url: []const u8,
    id: i64,
    tag_name: []const u8,
    assets_url: []const u8,
    updated_at: ?[]const u8 = null,
    author: @"simple-user",
    assets: []const @"release-asset",
    discussion_url: ?[]const u8 = null,
    reactions: ?@"reaction-rollup" = null,
    html_url: []const u8,
    node_id: []const u8,
    target_commitish: []const u8,
    zipball_url: ?[]const u8,
    immutable: ?bool = null,
    body: ?[]const u8 = null,
    name: ?[]const u8,
    draft: bool,
};

pub const @"simple-user" = struct {
    url: []const u8,
    subscriptions_url: []const u8,
    organizations_url: []const u8,
    email: ?[]const u8 = null,
    login: []const u8,
    gists_url: []const u8,
    events_url: []const u8,
    gravatar_id: ?[]const u8,
    id: i64,
    repos_url: []const u8,
    followers_url: []const u8,
    starred_url: []const u8,
    starred_at: ?[]const u8 = null,
    html_url: []const u8,
    node_id: []const u8,
    site_admin: bool,
    user_view_type: ?[]const u8 = null,
    following_url: []const u8,
    avatar_url: []const u8,
    name: ?[]const u8 = null,
    received_events_url: []const u8,
    type: []const u8,
};

pub const ProtectedBranchPullRequestReviewDismissalRestrictions = struct {
    users: ?[]const @"simple-user" = null,
    teams_url: ?[]const u8 = null,
    url: ?[]const u8 = null,
    teams: ?[]const team = null,
    users_url: ?[]const u8 = null,
    apps: ?[]const integration = null,
};

pub const ProtectedBranchPullRequestReviewBypassPullRequestAllowances = struct {
    users: ?[]const @"simple-user" = null,
    teams: ?[]const team = null,
    apps: ?[]const integration = null,
};

pub const @"protected-branch-pull-request-review" = struct {
    dismissal_restrictions: ?ProtectedBranchPullRequestReviewDismissalRestrictions = null,
    url: ?[]const u8 = null,
    dismiss_stale_reviews: bool,
    required_approving_review_count: ?i64 = null,
    bypass_pull_request_allowances: ?ProtectedBranchPullRequestReviewBypassPullRequestAllowances = null,
    require_code_owner_reviews: bool,
    require_last_push_approval: ?bool = null,
};

pub const NullableIssueReferenceIssueType = struct {
    color: ?[]const u8 = null,
    id: i64,
    node_id: []const u8,
    name: []const u8,
};

pub const @"nullable-issue-reference" = struct {
    repository: @"simple-repository",
    title: []const u8,
    number: i64,
    state: []const u8,
    state_reason: ?[]const u8 = null,
    issue_type: ?NullableIssueReferenceIssueType,
};

pub const @"page-deployment" = struct {
    status_url: []const u8,
    id: std.json.Value,
    page_url: []const u8,
    preview_url: ?[]const u8 = null,
};

pub const @"release-notes-content" = struct {
    name: []const u8,
    body: []const u8,
};

pub const @"referrer-traffic" = struct {
    referrer: []const u8,
    uniques: i64,
    count: i64,
};

pub const traffic = struct {
    timestamp: []const u8,
    uniques: i64,
    count: i64,
};

pub const @"custom-deployment-rule-app" = struct {
    integration_url: []const u8,
    id: i64,
    node_id: []const u8,
    slug: []const u8,
};

pub const @"webhook-config" = struct {
    content_type: ?[]const u8 = null,
    url: ?[]const u8 = null,
    insecure_ssl: ?@"webhook-config-insecure-ssl" = null,
    secret: ?[]const u8 = null,
};

pub const PullRequestStackMinimalPullRequestsItemHead = struct {
    sha: []const u8,
    ref: []const u8,
};

pub const PullRequestStackMinimalPullRequestsItem = struct {
    number: i64,
    state: []const u8,
    head: PullRequestStackMinimalPullRequestsItemHead,
    merged_at: ?[]const u8,
    draft: bool,
};

pub const PullRequestStackMinimalBase = struct {
    ref: []const u8,
};

pub const @"pull-request-stack-minimal" = struct {
    created_at: []const u8,
    url: []const u8,
    open: bool,
    node_id: []const u8,
    pull_requests: []const PullRequestStackMinimalPullRequestsItem,
    id: i64,
    base: PullRequestStackMinimalBase,
    number: i64,
};

pub const hook = struct {
    created_at: []const u8,
    active: bool,
    url: []const u8,
    events: []const []const u8,
    last_response: @"hook-response",
    id: i64,
    config: @"webhook-config",
    updated_at: []const u8,
    ping_url: []const u8,
    name: []const u8,
    test_url: []const u8,
    deliveries_url: ?[]const u8 = null,
    type: []const u8,
};

pub const @"merged-upstream" = struct {
    base_branch: ?[]const u8 = null,
    message: ?[]const u8 = null,
    merge_type: ?[]const u8 = null,
};

pub const CommunityProfileFiles = struct {
    code_of_conduct_file: @"nullable-community-health-file",
    license: @"nullable-license-simple",
    issue_template: @"nullable-community-health-file",
    code_of_conduct: @"nullable-code-of-conduct-simple",
    pull_request_template: @"nullable-community-health-file",
    contributing: @"nullable-community-health-file",
    readme: @"nullable-community-health-file",
};

pub const @"community-profile" = struct {
    description: ?[]const u8,
    files: CommunityProfileFiles,
    documentation: ?[]const u8,
    content_reports_enabled: ?bool = null,
    health_percentage: i64,
    updated_at: ?[]const u8,
};

pub const @"pull-request-stack-pull-request" = union(enum) {
    null,
    bool: bool,
    integer: i64,
    float: f64,
    number_string: []const u8,
    string: []const u8,
    array: std.json.Array,
    object: std.json.ObjectMap,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(_: std.mem.Allocator, source: std.json.Value, _: std.json.ParseOptions) !@This() {
        return switch (source) {
            .null => .null,
            .bool => |value| .{ .bool = value },
            .integer => |value| .{ .integer = value },
            .float => |value| .{ .float = value },
            .number_string => |value| .{ .number_string = value },
            .string => |value| .{ .string = value },
            .array => |value| .{ .array = value },
            .object => |value| .{ .object = value },
        };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .null => try jw.write(null),
            .bool => |value| try jw.write(value),
            .integer => |value| try jw.write(value),
            .float => |value| try jw.write(value),
            .number_string => |value| try jw.print("{s}", .{value}),
            .string => |value| try jw.write(value),
            .array => |value| try jw.write(value.items),
            .object => |value| {
                try jw.beginObject();
                var iterator = value.iterator();
                while (iterator.next()) |entry| {
                    try jw.objectField(entry.key_ptr.*);
                    try jw.write(entry.value_ptr.*);
                }
                try jw.endObject();
            },
        }
    }
};

pub const @"basic-error" = struct {
    status: ?[]const u8 = null,
    url: ?[]const u8 = null,
    message: ?[]const u8 = null,
    documentation_url: ?[]const u8 = null,
};

pub const StatusCheckPolicyChecksItem = struct {
    context: []const u8,
    app_id: ?i64,
};

pub const @"status-check-policy" = struct {
    url: []const u8,
    strict: bool,
    contexts: []const []const u8,
    checks: []const StatusCheckPolicyChecksItem,
    contexts_url: []const u8,
};

pub const @"nullable-issue-comment" = struct {
    created_at: []const u8,
    url: []const u8,
    issue_url: []const u8,
    body_html: ?[]const u8 = null,
    body_text: ?[]const u8 = null,
    performed_via_github_app: ?@"nullable-integration" = null,
    id: i64,
    user: @"nullable-simple-user",
    updated_at: []const u8,
    reactions: ?@"reaction-rollup" = null,
    html_url: []const u8,
    node_id: []const u8,
    author_association: ?[]const u8 = null,
    pin: ?@"nullable-pinned-issue-comment" = null,
    body: ?[]const u8 = null,
    minimized: ?@"nullable-issue-comment-minimized" = null,
};

pub const @"hook-response" = struct {
    status: ?[]const u8,
    message: ?[]const u8,
    code: ?i64,
};

pub const @"deploy-key" = struct {
    created_at: []const u8,
    url: []const u8,
    verified: bool,
    key: []const u8,
    read_only: bool,
    enabled: ?bool = null,
    added_by: ?[]const u8 = null,
    last_used: ?[]const u8 = null,
    id: i64,
    title: []const u8,
};

pub const ProtectedBranchBlockCreations = struct {
    enabled: bool,
};

pub const ProtectedBranchLockBranch = struct {
    enabled: ?bool = null,
};

pub const ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions = struct {
    users: []const @"simple-user",
    teams_url: []const u8,
    url: []const u8,
    teams: []const team,
    users_url: []const u8,
    apps: ?[]const integration = null,
};

pub const ProtectedBranchRequiredPullRequestReviewsBypassPullRequestAllowances = struct {
    users: []const @"simple-user",
    teams: []const team,
    apps: ?[]const integration = null,
};

pub const ProtectedBranchRequiredPullRequestReviews = struct {
    dismissal_restrictions: ?ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions = null,
    url: []const u8,
    dismiss_stale_reviews: ?bool = null,
    required_approving_review_count: ?i64 = null,
    bypass_pull_request_allowances: ?ProtectedBranchRequiredPullRequestReviewsBypassPullRequestAllowances = null,
    require_code_owner_reviews: ?bool = null,
    require_last_push_approval: ?bool = null,
};

pub const ProtectedBranchAllowForcePushes = struct {
    enabled: bool,
};

pub const ProtectedBranchAllowForkSyncing = struct {
    enabled: ?bool = null,
};

pub const ProtectedBranchEnforceAdmins = struct {
    url: []const u8,
    enabled: bool,
};

pub const ProtectedBranchRequiredLinearHistory = struct {
    enabled: bool,
};

pub const ProtectedBranchAllowDeletions = struct {
    enabled: bool,
};

pub const ProtectedBranchRequiredConversationResolution = struct {
    enabled: ?bool = null,
};

pub const ProtectedBranchRequiredSignatures = struct {
    url: []const u8,
    enabled: bool,
};

pub const @"protected-branch" = struct {
    block_creations: ?ProtectedBranchBlockCreations = null,
    url: []const u8,
    lock_branch: ?ProtectedBranchLockBranch = null,
    required_pull_request_reviews: ?ProtectedBranchRequiredPullRequestReviews = null,
    allow_force_pushes: ?ProtectedBranchAllowForcePushes = null,
    restrictions: ?@"branch-restriction-policy" = null,
    allow_fork_syncing: ?ProtectedBranchAllowForkSyncing = null,
    required_status_checks: ?@"status-check-policy" = null,
    enforce_admins: ?ProtectedBranchEnforceAdmins = null,
    required_linear_history: ?ProtectedBranchRequiredLinearHistory = null,
    allow_deletions: ?ProtectedBranchAllowDeletions = null,
    required_conversation_resolution: ?ProtectedBranchRequiredConversationResolution = null,
    required_signatures: ?ProtectedBranchRequiredSignatures = null,
};

pub const @"ruleset-version-with-state" = std.json.Value;

pub const @"commit-comparison" = struct {
    url: []const u8,
    behind_by: i64,
    status: []const u8,
    diff_url: []const u8,
    permalink_url: []const u8,
    patch_url: []const u8,
    files: ?[]const @"diff-entry" = null,
    html_url: []const u8,
    ahead_by: i64,
    total_commits: i64,
    base_commit: commit,
    merge_base_commit: commit,
    commits: []const commit,
};

pub const @"commit-comment" = struct {
    created_at: []const u8,
    url: []const u8,
    position: ?i64,
    commit_id: []const u8,
    line: ?i64,
    id: i64,
    user: @"nullable-simple-user",
    updated_at: []const u8,
    reactions: ?@"reaction-rollup" = null,
    html_url: []const u8,
    node_id: []const u8,
    author_association: []const u8,
    path: ?[]const u8,
    body: []const u8,
};

pub const autolink = struct {
    url_template: []const u8,
    is_alphanumeric: bool,
    key_prefix: []const u8,
    id: i64,
    updated_at: ?[]const u8 = null,
};

pub const @"nullable-pinned-issue-comment" = struct {
    pinned_by: @"nullable-simple-user",
    pinned_at: []const u8,
};

pub const @"page-build-status" = struct {
    status: []const u8,
    url: []const u8,
};

pub const @"deployment-status" = struct {
    created_at: []const u8,
    url: []const u8,
    state: []const u8,
    log_url: ?[]const u8 = null,
    repository_url: []const u8,
    performed_via_github_app: ?@"nullable-integration" = null,
    id: i64,
    creator: @"nullable-simple-user",
    environment_url: ?[]const u8 = null,
    updated_at: []const u8,
    environment: ?[]const u8 = null,
    deployment_url: []const u8,
    node_id: []const u8,
    target_url: []const u8,
    description: []const u8,
};

pub const @"issue-event-for-issue" = std.json.Value;

pub const @"rule-suitesItem" = struct {
    actor_name: ?[]const u8 = null,
    repository_id: ?i64 = null,
    actor_id: ?i64 = null,
    after_sha: ?[]const u8 = null,
    result: ?[]const u8 = null,
    before_sha: ?[]const u8 = null,
    repository_name: ?[]const u8 = null,
    pushed_at: ?[]const u8 = null,
    ref: ?[]const u8 = null,
    id: ?i64 = null,
    evaluation_result: ?[]const u8 = null,
};

pub const @"rule-suites" = []const @"rule-suitesItem";

pub const @"release-asset" = struct {
    created_at: []const u8,
    url: []const u8,
    state: []const u8,
    browser_download_url: []const u8,
    id: i64,
    updated_at: []const u8,
    size: i64,
    content_type: []const u8,
    digest: ?[]const u8,
    download_count: i64,
    uploader: @"nullable-simple-user",
    node_id: []const u8,
    name: []const u8,
    label: ?[]const u8,
};
