name: Changelog

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths:
      - ".github/workflows/changelog.yml"
      - "snapcraft.yaml"
      - "**/*.zig"
  release:
    types: [published]

jobs:
  changelog:
    if: github.ref == 'refs/heads/main' && github.repository == 'christianhelle/chlogr'
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Re-generate CHANGELOG.md
        run: zig build run -- --repo christianhelle/chlogr --token ${{ secrets.PAT }}

      - name: Git commit CHANGELOG.md
        run: |
          git config --global user.name "Continuous Integration"
          git config --global user.email "username@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Update changelog [skip ci]"
          git push
